### ISSUE TITLE
More in depth example?

### ISSUE THREAD

**Issue by acomito** [lorensr/login-links#2]
I'm confused at where to put the "final destination" URL.

Do I need to configure my FlowRouter routes to be cognizant of the token at the end of the URL?

if my normal route to get to the "post that Josh Owns commented on" is:

`https://myapp.com/anyroute?foo=bar` 

will FlowRouter act accordingly when somebody clicks on the link in their email that appears as: 

`https://myapp.com/anyroute?foo=bar&token=8888855555iAmRandoToken88887777`

Or am I passing the actual URL around somewhere else and doing a FlowRouter redirect or Flowrouter.Go after they login?

The documentation is nice I'm just having some trouble connecting the dots

**Comment by lorensr** [comment]
> Do I need to configure my FlowRouter routes to be cognizant of the token at the end of the URL?

Yes, on the client you need to do this:

https://github.com/lorensr/login-links#then-on-client

**Comment by lorensr** [comment]
The lib doesn't have any router-specific code, but I'd look at a PR!

**Comment by acomito** [comment]
Thanks for the fast response!

I understand that the lib doesn't have router-specific stuff enabled, if you find time to give a quick FlowRouter example, that'd be enough for the noobs like me! I'm not super clear on how/where the "then on client" should be enabled but will look into it more. Thanks for the cool package.

**Comment by lorensr** [comment]
I haven't used FR, but looks like it should be `FlowRouter.getQueryParam(queryStringKey);`

https://github.com/kadirahq/flow-router#flowroutergetqueryparamquerystringkey

``` js
if (!Meteor.userId()) {
  token = FlowRouter.getQueryParam('token');

  if (token) {
    LoginLinks.loginWithToken(token, function(e, r) {
      if (!e)
        // logged in!
    });
  }
}   
```

This is assuming `FlowRouter.getQueryParam('token');` is available at pageload time? Let me know if it works, and I'll put this example in the docs!

**Comment by acomito** [comment]
Will do. Thanks again

**Comment by JulianKingman** [comment]
Here's how to get it to work site-wide:

``` javascript
FlowRouter.triggers.enter([
  function (context) {
    if (context.queryParams.token && !Meteor.userId()) {
      console.log('logging in with token: ' + context.queryParams.token);
      LoginLinks.loginWithToken(context.queryParams.token, function(err){
        //yay, you should be logged in
      });
    }
  }
]);
```

**Comment by acomito** [comment]
thanks Julian!
