### ISSUE TITLE
Per Token Expiration Doesn't Work

### ISSUE THREAD

**Issue by nicholaai** [lorensr/login-links#3]
My setup:

Using Iron Router. On my route controller I have an onBeforeAction:

`if (!Meteor.user()) {
      var token = Router.current().params.token;

```
  if (token) {
    LoginLinks.connectionLogin(token, function(e, r) {
      if (!e) {
        return console.log(r);
      }
      return console.log(e);
    });
  }`
```

On my route I use: 

```
Router.route('/fillerRoute/fillerRoute/:token', {
  name: 'fillerTemplate',
  controller: UserController,
});

```

Meteor method to generate token:

```
var token = LoginLinks.generateAccessToken(user, {expiresInSeconds: 2 * 60});
switch (type) {
  case case1:
    return 'https://fillerAddress.com/fillerRoute/fillerRoute/' + token;
```

My issue here is that the login links never expire. When I console log out the result (in this case "r"), I get back an object with the properties of

expiresInSeconds: 120,
hashedToken: "unused"
userId: "QqTi4rWPkipHPmZtb",
when: Tue Jul 26 2016 13:58:11 GMT-0700 (PDT)

When I utilize the set global expiration method or set types method the expiration dates work. 

Also, I noticed that the login links work past one use, they only do not work when a token is expired. Is this the intended behavior? The description "The main use case is sending an email or sms to your user with a link to your app that contains an OTP (one-time password)" makes it seem like one user can use the link one time prior to the expiration point. 

Thanks for putting together the package!

**Comment by lorensr** [comment]
Hi! Thanks for reporting. Thought there was a test case that covered this,
but I'll look into it next week.

It is meant to be multi-use up until expiration, and I'll note this in the
readme

**Comment by lorensr** [comment]
Sorry for the delay. I've updated the readme. 

I've also added a new test for per-token expiration, which is passing. 

https://github.com/lorensr/login-links/blob/master/tests/client/loginHandler.js#L42-L56

Let me know if you're able to modify the test to get it to fail, or can reproduce in a blank meteor repo.

**Comment by kosst** [comment]
I think the problem is, that in the README.md (in the section for expiration per token) it's called `expiresInSeconds` but it has to be called `expirationInSeconds`.
